export const PRODUCT_CONTENT: Record<number, { description: string; features: string[] }> = {
  1: { description: "Single-Page SOP Template — Starter is a one-time digital purchase in our SOP Systems lineup, delivered by email immediately after checkout. It gives operators a clean, single-page format for documenting any repeatable procedure without clutter.", features: ["One clean single-page SOP layout, ready to fill in","Built for fast documentation of any repeatable task","Instant digital delivery by email after purchase","One-time payment — no further billing","Compatible with standard word processing and PDF software"] },
  2: { description: "Meeting Agenda Pack (10 Templates) is a one-time digital purchase in our Document Templates lineup, delivered by email immediately after checkout. It includes 10 structured agenda formats for standups, planning sessions, and leadership reviews.", features: ["Includes 10 structured meeting agenda formats","Covers standups, planning sessions, and leadership reviews","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Document Templates"] },
  3: { description: "Project Brief Document Template is a one-time digital purchase in our Document Templates lineup, delivered by email immediately after checkout. It gives teams a single, structured document for scoping objectives, timelines, and ownership before work begins.", features: ["One structured project brief document","Sections for scope, timeline, and ownership","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Document Templates"] },
  4: { description: "Client Onboarding Document Kit is a one-time digital purchase in our Document Templates lineup, delivered by email immediately after checkout. It bundles the intake forms, welcome documents, and expectation-setting templates needed to onboard a new client cleanly.", features: ["Includes intake forms and welcome documents","Includes an expectations and scope-of-work template","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Document Templates"] },
  5: { description: "Employee Handbook Starter Template is a one-time digital purchase in our Document Templates lineup, delivered by email immediately after checkout. It provides a structured starting framework covering policies, conduct, and onboarding expectations for a growing team.", features: ["Structured handbook framework covering core policies","Sections for conduct, benefits, and onboarding expectations","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Document Templates"] },
  6: { description: "Business Process Map Template Set is a one-time digital purchase in our Process Maps lineup, delivered by email immediately after checkout. It includes editable flowchart-style templates for mapping how work actually moves through your organization.", features: ["Editable flowchart-style process map templates","Designed to visualize handoffs and decision points","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Process Maps"] },
  7: { description: "Standard Operating Procedure Library (20 SOPs) is a one-time digital purchase in our SOP Systems lineup, delivered by email immediately after checkout. It includes 20 ready-to-customize SOP documents spanning common operational functions.", features: ["Includes 20 ready-to-customize SOP documents","Spans common operational functions across a business","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: SOP Systems"] },
  8: { description: "Department Operations Manual Template is a one-time digital purchase in our SOP Systems lineup, delivered by email immediately after checkout. It gives department leads a single organized manual structure for documenting how their team operates day to day.", features: ["One organized department operations manual structure","Built for documenting day-to-day team operations","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: SOP Systems"] },
  9: { description: "Vendor & Supplier Agreement Framework is a one-time digital purchase in our Document Templates lineup, delivered by email immediately after checkout. It includes structured agreement and evaluation templates for formalizing vendor and supplier relationships.", features: ["Structured vendor and supplier agreement templates","Includes a supplier evaluation checklist template","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Document Templates"] },
  10: { description: "Complete HR Document Pack is a one-time digital purchase in our Business Kits lineup, delivered by email immediately after checkout. It bundles the core hiring, onboarding, and personnel documentation a growing team needs in one organized pack.", features: ["Bundles core hiring and onboarding documents","Includes personnel and policy documentation templates","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Business Kits"] },
  11: { description: "Business Playbook Template System is a one-time digital purchase in our Business Kits lineup, delivered by email immediately after checkout. It provides a structured playbook framework for capturing how your business runs, department by department.", features: ["Structured playbook framework across departments","Designed to capture institutional operating knowledge","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Business Kits"] },
  12: { description: "Full Operations Document Suite is a one-time digital purchase in our Business Kits lineup, delivered by email immediately after checkout. It combines SOPs, process maps, and operations manuals into a single comprehensive document suite.", features: ["Combines SOPs, process maps, and manuals in one suite","Built for teams standardizing operations end to end","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Business Kits"] },
  13: { description: "Franchise Operations Manual Template is a one-time digital purchase in our SOP Systems lineup, delivered by email immediately after checkout. It gives multi-location operators a consistent manual framework for training and running every location the same way.", features: ["Consistent operations manual framework for multiple locations","Built for training and location-to-location standardization","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: SOP Systems"] },
  14: { description: "Enterprise SOP + Process Map Bundle is a one-time digital purchase in our Process Maps lineup, delivered by email immediately after checkout. It pairs a full SOP library with matching process map templates for organizations documenting operations at scale.", features: ["Pairs a full SOP library with matching process maps","Built for organizations documenting operations at scale","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Process Maps"] },
  15: { description: "Complete Business Document Library is a one-time digital purchase in our Business Kits lineup, delivered by email immediately after checkout. It includes our full catalog of document templates, SOPs, and process maps in a single organized library.", features: ["Includes our full catalog of templates, SOPs, and maps","One organized library covering every document category","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Business Kits"] },
  16: { description: "Ultimate Workflow & Operations System is a one-time digital purchase in our Business Kits lineup, delivered by email immediately after checkout. It is our most complete system, combining every template, SOP, and process map into a single end-to-end operations system.", features: ["Our most complete document and operations system","Combines every template, SOP, and process map we offer","Instant digital delivery by email after purchase","One-time payment — no further billing","Category: Business Kits"] }
};
