export interface ProductSections {
  overview: string;
  whatsIncluded: string[];
  templateFeatures: string[];
  compatibleSoftware: string[];
  idealFor: string[];
  keyBenefits: string[];
  fileFormats: string[];
  customizationOptions: string[];
}

export const PRODUCT_CONTENT: Record<number, ProductSections> = {
  1: {
    overview:
      "The Single-Page SOP Template — Starter is a streamlined document system built for operators who need to capture repeatable procedures without the weight of a full manual. Presented as a clean, structured single page, it gives your team a consistent format for step-by-step instructions, role assignments, approval fields, and troubleshooting notes. Whether you're documenting a daily opening checklist or a quarterly compliance routine, this template keeps everything on one page so it can be printed, pinned, or shared instantly.",
    whatsIncluded: [
      "One single-page SOP template with guided sections",
      "Header fields for procedure name, owner, and revision date",
      "Step-by-step task table with numbering and checkboxes",
      "Tools, materials, and safety notes section",
      "Approval and review signature block",
      "Issue log and corrective action notes area",
    ],
    templateFeatures: [
      "Standard letter and A4 page layouts",
      "Pre-defined styles for headings, body text, and callouts",
      "Editable tables with calculation-ready cells",
      "Printable in grayscale or color",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Apple Pages", "PDF"],
    idealFor: [
      "Solopreneurs documenting daily operational routines",
      "Small teams standardizing one critical recurring task",
      "Shift managers needing a printable quick-reference sheet",
    ],
    keyBenefits: [
      "Cuts training time by replacing oral instructions with written steps",
      "Ensures consistency across shifts, locations, and staff turnover",
      "Ready to customize in minutes, no professional designer needed",
      "Fits on a single page for quick review and deployment",
    ],
    fileFormats: ["Word (.docx)", "PDF"],
    customizationOptions: [
      "Add your company logo and brand colors",
      "Adjust section headings to match internal terminology",
      "Insert hyperlinks to training videos or shared drives",
      "Lock or unlock specific fields for end-user editing",
    ],
  },
  2: {
    overview:
      "The Meeting Agenda Pack (10 Templates) is a curated set of meeting structures designed to replace ad-hoc agendas with consistent, purpose-built formats. From daily standups to quarterly business reviews, each template guides your team through time allocation, discussion topics, decision tracking, and action accountability. The pack gives leaders twelve months of ready-to-use agenda structures that keep meetings on time and on purpose.",
    whatsIncluded: [
      "Ten distinct meeting agenda templates",
      "Daily standup format (15-minute sync structure)",
      "Weekly team alignment template",
      "Monthly planning session agenda",
      "Quarterly business review format",
      "Leadership and board meeting agenda",
      "Project kickoff meeting structure",
      "One-on-one meeting template",
      "Retrospective and post-mortem format",
      "All-hands and town hall agenda",
    ],
    templateFeatures: [
      "Consistent header with date, attendees, and objectives",
      "Time-boxed sections with suggested durations",
      "Decision log and parking lot sections",
      "Action item tracker with owner and due date",
      "Prep checklist sent ahead of the meeting",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "Apple Pages", "PDF"],
    idealFor: [
      "Startup founders running structured meetings",
      "Operations managers standardizing recurring team syncs",
      "Department leads who need flexible agenda formats",
    ],
    keyBenefits: [
      "Reduces meeting drift by giving every discussion a time box",
      "Creates written records so decisions survive staff turnover",
      "Covers the most common meeting types in one purchase",
      "Professional layout that reflects well on the meeting host",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Rebrand with your logo and letterhead",
      "Add or remove sections for your team's workflow",
      "Create duplicates for recurring meetings (weekly, monthly)",
      "Integrate with calendar invites by pasting the agenda inline",
    ],
  },
  3: {
    overview:
      "The Project Brief Document Template gives project leads a single, authoritative starting point for every new initiative. Instead of scattering scope, timelines, and ownership across chat threads and emails, this template captures the full project context in one structured document. Stakeholders can approve scope before work starts, and team members can reference the same brief from kickoff to delivery without chasing status updates.",
    whatsIncluded: [
      "One editable project brief document",
      "Project overview and executive summary sections",
      "Scope definition with in-scope and out-of-scope lists",
      "Timeline and milestone tracker",
      "Stakeholder register with ownership and decision rights",
      "Budget placeholder and resource allocation section",
      "Risk assessment and mitigation table",
      "Success criteria and acceptance standards",
    ],
    templateFeatures: [
      "Clean, scannable layout with clear visual hierarchy",
      "Editable tables for timelines and budgets",
      "Built-in sign-off section for stakeholder approval",
      "Conditional formatting-ready structure",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "PDF"],
    idealFor: [
      "Product managers kicking off new features",
      "Project leads coordinating cross-functional initiatives",
      "Agencies aligning clients on scope before work begins",
    ],
    keyBenefits: [
      "Prevents scope creep by documenting approvals in writing",
      "Aligns stakeholders before resources are committed",
      "Provides a single source of truth for the full project lifecycle",
      "Professional enough for client presentations",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Duplicate and save a master template per project type",
      "Add approval workflows as conditional forms",
      "Embed links to shared drives and project boards",
      "Adjust sections for different industries or methodologies",
    ],
  },
  4: {
    overview:
      "The Client Onboarding Document Kit bundles the essential intake, welcome, and expectation-setting templates needed to move a new client from first contact to active engagement without dropping details. Rather than cobbling together forms and emails, this kit gives you a repeatable onboarding workflow that sets clear expectations, collects necessary information, and makes every new client feel professionally welcomed from day one.",
    whatsIncluded: [
      "Client intake and discovery questionnaire",
      "Welcome letter and onboarding confirmation template",
      "Scope of work and service agreement outline",
      "Contact and emergency information form",
      "Brand and asset request checklist",
      "Timeline and project launch schedule",
      "Client communication preferences form",
      "Follow-up and feedback request template",
    ],
    templateFeatures: [
      "Fillable fields for digital completion",
      "Consistent branding and tone across all documents",
      "Sequential numbering and logical flow",
      "Email-ready formatting for easy delivery",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Canva", "PDF"],
    idealFor: [
      "Freelancers and solopreneurs scaling client acquisition",
      "Agencies standardizing client intake across account managers",
      "Consultants who need a professional first impression",
    ],
    keyBenefits: [
      "Reduces onboarding time with a proven, repeatable workflow",
      "Eliminates follow-up emails asking for missing information",
      "Projects professionalism and organization to every new client",
      "Fully customizable to match your service offering",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Canva", "PDF"],
    customizationOptions: [
      "Add your logo and brand colors to every document",
      "Customize intake questions to match your service tiers",
      "Create electronic signature fields using DocuSign or similar",
      "Duplicate for different client types or service lines",
    ],
  },
  5: {
    overview:
      "The Employee Handbook Starter Template provides a professional, structured foundation for documenting company policies, employee conduct expectations, benefits, and onboarding protocols. Designed for businesses that have outgrown verbal policy explanations, this template gives HR leaders and founders a compliant framework that can be customized to reflect your unique culture, benefits, and operational procedures. It balances legal structure with accessible language so employees actually read and understand it.",
    whatsIncluded: [
      "Table of contents with auto-linked sections",
      "Welcome and company mission statement section",
      "Employment classification and equal opportunity policies",
      "Code of conduct and workplace expectations",
      "Benefits, time off, and leave policies",
      "Health, safety, and emergency procedures",
      "Performance expectations and review cycles",
      "Acknowledgment and receipt page",
    ],
    templateFeatures: [
      "Modular section layout for easy additions and updates",
      "Policy numbering system for cross-referencing",
      "Editable tables for benefits and holiday schedules",
      "Print-ready and email-shareable formats",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Apple Pages", "PDF"],
    idealFor: [
      "Startup founders building their first employee handbook",
      "HR managers updating or digitizing an outdated handbook",
      "Growing teams adding structure to employee onboarding",
    ],
    keyBenefits: [
      "Establishes clear expectations and reduces HR ambiguity",
      "Professional appearance that builds employee trust",
      "Modular design lets you add sections as your company grows",
      "Legal framework that supports compliance and fair treatment",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Apple Pages", "PDF"],
    customizationOptions: [
      "Tailor policies to state and local employment laws",
      "Add company-specific benefits and PTO policies",
      "Include photos, team values, and culture pages",
      "Create digital versions with clickable table of contents",
    ],
  },
  6: {
    overview:
      "The Business Process Map Template Set provides a collection of editable flowchart-style templates designed to visualize how work actually moves through your organization. Rather than describing processes in paragraphs, these maps give teams a visual language for handoffs, decision points, approvals, and bottlenecks. Use them to document existing workflows, identify inefficiencies, and train new hires on how work should flow from step to step.",
    whatsIncluded: [
      "Linear process flow template",
      "Swimlane cross-functional map template",
      "Decision-tree flowchart template",
      "Input-output process diagram template",
      "Milestone and phase-gate template",
      "RACI-style responsibility assignment map",
      "Root cause analysis diagram",
      "Process improvement before-and-after map",
    ],
    templateFeatures: [
      "Drag-and-drop flowchart shapes and connectors",
      "Color-coded swimlanes for different departments",
      "Decision diamond templates with Yes / No paths",
      "Connection lines that snap to grid for clean alignment",
    ],
    compatibleSoftware: ["Microsoft Visio", "Lucidchart", "Diagram.net", "Canva", "PowerPoint"],
    idealFor: [
      "Operations teams mapping current-state workflows",
      "Project managers designing approval or escalation paths",
      "Lean practitioners documenting value streams",
    ],
    keyBenefits: [
      "Turns tribal knowledge into visual instructions anyone can follow",
      "Exposes bottlenecks and redundancies in existing workflows",
      "Professional enough for board presentations and audits",
      "Saves hours of manual diagramming",
    ],
    fileFormats: ["Visio (.vsdx)", "PDF", "PowerPoint (.pptx)", "Canva"],
    customizationOptions: [
      "Adjust shapes, colors, and labels to match your branding",
      "Add or remove process steps as workflows evolve",
      "Export as high-resolution images for presentations",
      "Link to supporting documents in shared workspaces",
    ],
  },
  7: {
    overview:
      "The Standard Operating Procedure Library (20 SOPs) is the most practical entry point into formalized operations. This collection includes twenty ready-to-customize SOPs covering the functions most businesses need documented immediately—from employee onboarding and customer support to inventory management and quality assurance. Each SOP follows a consistent structure, so your team learns one format and applies it everywhere.",
    whatsIncluded: [
      "Customer onboarding SOP",
      "New hire onboarding SOP",
      "Daily opening and closing checklist SOP",
      "Quality inspection SOP",
      "Inventory management and stock count SOP",
      "Customer support escalation SOP",
      "Incident reporting SOP",
      "Content publishing workflow SOP",
      "Financial reconciliation SOP",
      "Equipment maintenance SOP",
      "Data backup and recovery SOP",
      "Client follow-up SOP",
      "Expense reporting SOP",
      "Vendor evaluation SOP",
      "Training delivery SOP",
      "Compliance audit checklist SOP",
      "Social media management SOP",
      "Meeting facilitation SOP",
      "Return and refund processing SOP",
      "Product launch checklist SOP",
    ],
    templateFeatures: [
      "Standardized SOP format across all 20 documents",
      "Numbered steps, responsible roles, and frequency fields",
      "Revision history table on every SOP",
      "Printable and digital-ready layouts",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "PDF"],
    idealFor: [
      "Businesses formalizing operations for the first time",
      "Teams preparing for audits, certifications, or scaling",
      "Founders who need documented processes before hiring",
    ],
    keyBenefits: [
      "Twenty core SOPs for the price of one, covering your busiest functions",
      "Consistent structure means zero format debates",
      "Ready to customize and deploy immediately",
      "Builds a culture of written accountability",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Adapt language and steps to your exact workflow",
      "Insert your logo and company branding",
      "Create a custom numbering and naming system",
      "Combine related SOPs into larger operations manuals",
    ],
  },
  8: {
    overview:
      "The Department Operations Manual Template gives department leads a structured, organized manual framework for documenting how their team operates day to day. Whether you're in operations, customer success, marketing, or finance, this template helps you capture responsibilities, workflows, key metrics, and team rhythms in one place. It's designed to be handed to a new manager or department head so they can understand and inherit the operation without a multi-month transition period.",
    whatsIncluded: [
      "Department overview and mission section",
      "Team structure and reporting lines",
      "Core operational workflows and process maps",
      "Key performance indicators and reporting cadence",
      "Resources, tools, and systems inventory",
      "Roles and responsibilities matrix",
      "Meeting rhythm and decision rights",
      "Emergency procedures and escalation paths",
    ],
    templateFeatures: [
      "Department-specific layout with clear section hierarchy",
      "Editable org chart and RACI table templates",
      "Dashboard-ready KPI tracker with metric definitions",
      "Resource inventory table with access instructions",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "PDF"],
    idealFor: [
      "Department heads documenting their operational model",
      "Operations and customer success teams scaling structure",
      "Managers inheriting a new department or region",
    ],
    keyBenefits: [
      "Accelerates manager onboarding by weeks instead of months",
      "Creates a durable record that survives turnover",
      "Aligns the team on roles, metrics, and escalation paths",
      "Professional document suitable for review by leadership",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Rebrand with department logos and color coding",
      "Add department-specific SOP references and links",
      "Include screenshots and walkthroughs of internal tools",
      "Create version-controlled updates for quarterly reviews",
    ],
  },
  9: {
    overview:
      "The Vendor & Supplier Agreement Framework provides structured templates for formalizing vendor and supplier relationships with clear terms, responsibilities, and evaluation criteria. Whether you're onboarding a new software provider or reviewing a physical supplier contract, this framework ensures every relationship starts with mutual understanding—covering service levels, confidentiality, payment terms, and performance evaluation in one organized package.",
    whatsIncluded: [
      "Standard vendor service agreement template",
      "Master service agreement outline",
      "Non-disclosure and confidentiality agreement",
      "Supplier performance evaluation checklist",
      "Service level agreement (SLA) template",
      "Request for proposal (RFP) response tracker",
      "Vendor onboarding checklist",
      "Contract renewal and exit evaluation form",
    ],
    templateFeatures: [
      "Clause-ready legal structure with placeholder areas",
      "Editable terms for services, fees, and termination",
      "Built-in evaluation scoring tables",
      "Signature and witness block formatting",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "PDF"],
    idealFor: [
      "Procurement teams formalizing vendor relationships",
      "Operations managers managing multiple suppliers",
      "Legal and compliance teams standardizing contract review",
    ],
    keyBenefits: [
      "Reduces contract review time with pre-structured agreements",
      "Ensures consistent terms across all vendor relationships",
      "Protects the business with standard legal provisions",
      "Streamlines supplier onboarding and evaluation",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "PDF"],
    customizationOptions: [
      "Adapt clauses to your legal review and jurisdiction",
      "Add company-specific insurance and liability requirements",
      "Insert branding and letterhead",
      "Create clause libraries for different vendor categories",
    ],
  },
  10: {
    overview:
      "The Complete HR Document Pack is a comprehensive collection of hiring, onboarding, and personnel documentation templates designed for growing teams that have outgrown ad-hoc processes. From job descriptions and offer letters to performance reviews and offboarding checklists, this pack gives HR managers and founders a complete document library that stays consistent from candidate outreach through employee exit. Every template is written in clear, compliant language and formatted for professional presentation.",
    whatsIncluded: [
      "Job description templates (multiple roles)",
      "Employment offer letter template",
      "New hire paperwork checklist",
      "Employee personal information form",
      "NDA and confidentiality agreement",
      "Employee handbook acknowledgment form",
      "Performance review template (annual and quarterly)",
      "Disciplinary action documentation form",
      "Employee exit interview checklist",
      "Final pay and return-of-property form",
    ],
    templateFeatures: [
      "Compliant language optimized for US employment standards",
      "Consistent formatting across all HR documents",
      "Checklist-style layouts for onboarding and exit",
      "Signature-ready agreement templates",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "PDF"],
    idealFor: [
      "Growing startups building their first HR library",
      "Small business owners managing hiring without HR staff",
      "HR managers standardizing people operations",
    ],
    keyBenefits: [
      "Covers the full employee lifecycle in one organized pack",
      "Reduces administrative time with ready-to-send templates",
      "Professional templates that reflect well on your employer brand",
      "Consistent documentation protects against compliance gaps",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "PDF"],
    customizationOptions: [
      "Edit roles, benefits, and policy language to match your company",
      "Add your logo and branded letterhead",
      "Create role-specific offer letter templates",
      "Adapt review forms for different performance frameworks",
    ],
  },
  11: {
    overview:
      "The Business Playbook Template System is a structured framework for capturing how your business actually runs, department by department. Rather than storing tribal knowledge in individual heads, this system gives founders and operators a repeatable playbook format that covers everything from marketing workflows to sales scripts, customer support protocols, and product release procedures. It's the closest thing to a written business operating system.",
    whatsIncluded: [
      "Core business playbook structure and table of contents",
      "Marketing playbook section template",
      "Sales playbook and objection-handling template",
      "Customer support playbook template",
      "Product and engineering playbook template",
      "Finance and operations playbook template",
      "People and culture playbook template",
      "Performance tracking and review section",
    ],
    templateFeatures: [
      "Department-specific section architecture",
      "Editable playbook templates with consistent formatting",
      "Cheat sheet and quick-reference inserts",
      "Version control and update log templates",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "PDF"],
    idealFor: [
      "Founders capturing institutional knowledge before scaling",
      "Operations teams standardizing department functions",
      "Consultants delivering structured playbooks to clients",
    ],
    keyBenefits: [
      "Survives staff turnover by documenting how work gets done",
      "Unifies department language and expectations",
      "Reduces training time for new hires and managers",
      "Built for continuous improvement and versioning",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Build out one section at a time as each department matures",
      "Add department-specific scripts and template libraries",
      "Embed links to external tools and shared resources",
      "Create read-only viewer versions for new hires and contractors",
    ],
  },
  12: {
    overview:
      "The Full Operations Document Suite combines standard operating procedures, process maps, and operations manuals into a single comprehensive package for teams standardizing their operations end to end. Rather than buying these components separately, this suite gives you a unified library where every SOP, process map, and manual follows the same structure. It is the right choice for operations teams that have moved beyond patchwork documentation and are ready for a cohesive system.",
    whatsIncluded: [
      "Twenty canonical SOP templates",
      "Eighteen process map templates (flowcharts and swimlanes)",
      "Four department operations manual structures",
      "RACI and responsibility matrix templates",
      "Meeting cadence and review schedule templates",
      "Performance dashboard and KPI tracker",
      "Issue log and continuous improvement log",
      "Master index and document control framework",
    ],
    templateFeatures: [
      "Unified numbering and naming convention across all documents",
      "Cross-linked table of contents and master index",
      "Consistent branding and formatting throughout",
      "Version control log for every document type",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Microsoft Visio", "Notion", "PDF"],
    idealFor: [
      "Mid-size companies formalizing their entire operations layer",
      "Operations directors preparing for audits or certifications",
      "Teams migrating from tribal knowledge to written systems",
    ],
    keyBenefits: [
      "Everything in one package with consistent structure",
      "Eliminates the time cost of selecting individual templates",
      "Creates an operations backbone that scales with the business",
      "Professional enough for leadership review and investor audits",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Visio (.vsdx)", "Notion", "PDF"],
    customizationOptions: [
      "Add or remove SOPs based on your operational priorities",
      "Create department-specific sub-libraries",
      "Brand the entire suite with your company standards",
      "Link process maps to their corresponding SOP pages",
    ],
  },
  13: {
    overview:
      "The Franchise Operations Manual Template gives multi-location operators a consistent, repeatable manual framework for training, running, and evaluating every location the same way. Franchise operators know that inconsistent execution is the fastest way to erode brand value. This manual ensures every location owner and manager receives the same structured guidance on standards, procedures, marketing, and compliance—protecting your brand while giving franchisees a clear roadmap to success.",
    whatsIncluded: [
      "Franchise overview and brand standards section",
      "Daily, weekly, and monthly operational checklists by department",
      "Training program and certification tracker",
      "Quality assurance and audit checklist",
      "Marketing and local advertising guidelines",
      "Financial and reporting requirements template",
      "Supplier and procurement standards",
      "Franchisee compliance and renewal review",
    ],
    templateFeatures: [
      "Multi-location scalable structure",
      "Checklist-based execution pages for managers",
      "Audit and compliance scoring templates",
      "Read-only field guides for franchisee staff",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "PDF"],
    idealFor: [
      "Franchisors building their first operations manual",
      "Multi-location restaurant, retail, or service operators",
      "Franchise consultants delivering compliance-ready documents",
    ],
    keyBenefits: [
      "Protects brand consistency across every location",
      "Reduces franchisee support time with self-service documentation",
      "Structured enough for legal and insurance review",
      "Supports scalable training without reinventing content",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "PDF"],
    customizationOptions: [
      "Adapt standards to your industry and brand requirements",
      "Create location-specific addenda and supplements",
      "Add franchise fee and royalty calculation tables",
      "Include video and image placeholders for franchisee reference",
    ],
  },
  14: {
    overview:
      "The Enterprise SOP + Process Map Bundle is built for organizations documenting operations at scale. This bundle pairs a full SOP library with matching process map templates, giving you two complementary views of every major workflow: the written procedure and the visual flowchart. Enterprise teams use this bundle to standardize complex, cross-functional operations while maintaining the ability to visualize handoffs, data flows, and decision paths for leadership review, audits, and continuous improvement.",
    whatsIncluded: [
      "Thirty enterprise-grade SOP templates",
      "Thirty matching process map templates (flowcharts and swimlanes)",
      "Cross-functional workflow documentation guide",
      "Data flow and system integration map templates",
      "Risk assessment and control matrix",
      "Document control and master index",
      "Change request and SOP update tracker",
      "Audit and compliance review templates",
    ],
    templateFeatures: [
      "Enterprise-grade formatting with executive-ready polish",
      "Layered documentation: summary, detailed, and visual views",
      "Advanced tables for risks, controls, and KPIs",
      "Archived change management and revision tracking",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Microsoft Visio", "Lucidchart", "PDF"],
    idealFor: [
      "Enterprise operations teams documenting complex workflows",
      "Organizations preparing for ISO, SOC 2, or compliance audits",
      "Consultants implementing operations frameworks at scale",
    ],
    keyBenefits: [
      "Two complementary views of every major workflow",
      "Meets the documentation depth expected by enterprise auditors",
      "Scales across departments and geographies",
      "Reduces consulting costs by providing a complete starting framework",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Visio (.vsdx)", "Lucidchart", "PDF"],
    customizationOptions: [
      "Create department-specific SOP libraries",
      "Integrate process maps with your internal wiki or intranet",
      "Build approval workflows for SOP changes",
      "Develop SOP templates for new business units as you expand",
    ],
  },
  15: {
    overview:
      "The Complete Business Document Library is the definitive catalog of document templates, SOPs, and process maps in one organized, searchable collection. Instead of purchasing individual systems, this library gives you access to every template type in the catalog—from single-page SOPs to full operations manuals—so you can assemble exactly the documentation stack your business needs. It is the centerpiece of a professional operations infrastructure.",
    whatsIncluded: [
      "All document templates from the Template category",
      "All SOP systems across all pricing tiers",
      "All process map sets and flowchart libraries",
      "All business kit collections",
      "Master index and quick-reference guide",
      "Style guide and formatting standards",
      "Template usage and best-practice guide",
      "Regular update notifications as the library expands",
    ],
    templateFeatures: [
      "Unified master index with hyperlinked navigation",
      "Consistent formatting and naming across all collections",
      "Modular design lets you assemble custom kits",
      "Frequently updated with new templates and formats",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "Canva", "Microsoft Visio", "PDF"],
    idealFor: [
      "Operations professionals who need access to every template type",
      "Businesses that want to assemble custom documentation stacks",
      "Consultants delivering comprehensive client documentation",
    ],
    keyBenefits: [
      "The most complete single-purchase documentation library available",
      "Modular enough to build exactly what you need",
      "Saves money compared to purchasing systems separately",
      "Grows with your business as you add new documentation needs",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "Canva", "Visio (.vsdx)", "PDF"],
    customizationOptions: [
      "Assemble custom kits from template subsets",
      "Create white-labeled versions for client delivery",
      "Add internal SOPs to the master index",
      "Build department-specific plays from the template library",
    ],
  },
  16: {
    overview:
      "The Ultimate Workflow & Operations System is the most comprehensive document and operations package available, combining every template, SOP, and process map into a single end-to-end operations system. This is the system for organizations that are no longer experimenting with documentation and are ready to deploy a complete, structured infrastructure that covers onboarding, operations, quality, compliance, and continuous improvement. It is the operational backbone that fast-growing businesses outgrow everything else to acquire.",
    whatsIncluded: [
      "All fifty-plus document templates from the full catalog",
      "All SOP systems and process map libraries",
      "All business kit collections and automation frameworks",
      "Enterprise operations manual framework",
      "Business playbook and knowledge management system",
      "Franchise and multi-location operations manual",
      "Continuous improvement and Kaizen tracking system",
      "Master index, style guide, and governance framework",
      "Implementation roadmap and rollout guide",
      "Priority access to future template updates",
    ],
    templateFeatures: [
      "Enterprise-grade design with executive polish",
      "Integrates every template, SOP, and map into one system",
      "Built-in governance, version control, and update cadence",
      "Implementation roadmap and change management guide",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "Canva", "Microsoft Visio", "Lucidchart", "PDF"],
    idealFor: [
      "Fast-growing companies formalizing their entire operations stack",
      "Enterprise teams needing a complete documentation ecosystem",
      "Consultants delivering turnkey operational systems to clients",
    ],
    keyBenefits: [
      "The only purchase you need for a complete operations library",
      "Eliminates search costs and integration gaps between systems",
      "Designed for scale, audit, and investor readiness",
      "Future-proof with included updates and new template access",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "Canva", "Visio (.vsdx)", "Lucidchart", "PDF"],
    customizationOptions: [
      "Assemble subsets for specific business units or divisions",
      "Brand the entire system to your corporate identity",
      "Add proprietary templates and integrate with your wiki",
      "Create implementation phases for large-scale rollouts",
    ],
  },
};
