export interface ProductSections {
  overview: string;
  whatsIncluded: string[];
  templateFeatures: string[];
  compatibleSoftware: string[];
  idealFor: string[];
  keyBenefits: string[];
  fileFormats: string[];
  customizationOptions: string[];
}

export const PRODUCT_CONTENT: Record<number, ProductSections> = {
  1: {
    overview:
      "The Single-Page SOP Template — Starter is a precision-engineered document designed for operators who need to capture standard operating procedures without the overhead of a full manual. Packed into one clean, scannable page, it provides structured fields for process steps, responsibility assignments, tool requirements, safety notes, and approval sign-offs. Ideal for daily opening rituals, equipment checks, or safety routines, this template ensures every task is documented consistently and can be printed, pinned, or shared instantly.",
    whatsIncluded: [
      "One single-page SOP starter template",
      "Procedure name, owner, and revision date header fields",
      "Numbered task list with checkbox completion fields",
      "Required tools, materials, and safety consideration section",
      "Approval, review, and signature blocks",
      "Issue tracking and corrective action notes area",
    ],
    templateFeatures: [
      "Standard letter and A4 page layouts",
      "Pre-formatted heading and body text styles",
      "Editable tables with clear column structure",
      "Print-ready formatting for grayscale or color output",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Apple Pages", "PDF"],
    idealFor: [
      "Solopreneurs documenting daily operational routines",
      "Small teams standardizing one critical recurring task",
      "Shift managers who need a printable quick-reference sheet",
    ],
    keyBenefits: [
      "Replaces oral instructions with written, repeatable steps",
      "Ensures consistency across shifts, locations, and staff turnover",
      "Customizable in minutes without design software",
      "Fits on a single page for rapid review and deployment",
    ],
    fileFormats: ["Word (.docx)", "PDF"],
    customizationOptions: [
      "Add company logos and brand color accents",
      "Adjust section labels to match internal terminology",
      "Insert hyperlinks to training videos or shared drives",
      "Lock unused fields while keeping editable sections for the team",
    ],
  },
  2: {
    overview:
      "The Meeting Agenda Pack (10 Templates) gives leaders a complete library of structured meeting formats—ten distinct documents built to eliminate ad-hoc agendas and keep every discussion on time and on purpose. From 15-minute daily standups to quarterly business reviews and leadership retrospectives, each template includes time-boxed sections, decision trackers, and action item fields that turn meetings into accountable working sessions.",
    whatsIncluded: [
      "Ten meeting agenda templates covering common business meeting types",
      "Daily standup structure with time-boxed sync fields",
      "Weekly team alignment and planning session templates",
      "Monthly review and quarterly business review formats",
      "Leadership and board meeting agenda",
      "Project kickoff meeting structure",
      "One-on-one and mentorship meeting template",
      "Retrospective and post-mortem format",
      "All-hands and town hall agenda",
      "Decision log and parking lot tracking sections",
    ],
    templateFeatures: [
      "Consistent header fields for date, attendees, and meeting objectives",
      "Time-boxed discussion sections with suggested durations",
      "Decision tracking and action item owner fields",
      "Parking lot capture for off-topic items",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "Apple Pages", "PDF"],
    idealFor: [
      "Startup founders who run structured recurring meetings",
      "Operations managers standardizing team syncs across departments",
      "Executive assistants and department leads",
    ],
    keyBenefits: [
      "Reduces meeting drift with enforced time allocation",
      "Creates written records that survive staff turnover",
      "Professional presentation that reflects well on the meeting host",
      "Covers the most common meeting types in one purchase",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Rebrand with company logo and letterhead",
      "Add or remove sections to match your meeting cadence",
      "Duplicate templates for weekly, monthly, and quarterly repeats",
      "Integrate agendas directly into calendar invites",
    ],
  },
  3: {
    overview:
      "The Project Brief Document Template gives project leads a single, authoritative starting document for every new initiative. Instead of scattering scope, timelines, and ownership across chat threads and fragmented notes, this template captures the complete project context in one structured layout. Stakeholders can approve scope before work begins, and the brief becomes the single source of truth referenced from kickoff through delivery.",
    whatsIncluded: [
      "One editable project brief document",
      "Project overview and executive summary sections",
      "Scope definition with explicit in-scope and out-of-scope lists",
      "Timeline and milestone tracker table",
      "Stakeholder and decision-maker register",
      "Budget placeholder and resource allocation section",
      "Risk assessment and mitigation table",
      "Success criteria and acceptance standards",
    ],
    templateFeatures: [
      "Clean, scannable layout with clear visual hierarchy",
      "Editable tables for timelines, budgets, and milestones",
      "Built-in sign-off section for stakeholder approval",
      "Conditional formatting structure ready for status tracking",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "PDF"],
    idealFor: [
      "Product managers kicking off new features or initiatives",
      "Project leads coordinating cross-functional work",
      "Agencies aligning clients on scope before engagement",
    ],
    keyBenefits: [
      "Prevents scope creep by documenting approvals in writing",
      "Aligns stakeholders before resources are committed",
      "Single source of truth for the full project lifecycle",
      "Professional enough for client presentations",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Duplicate and save a master template per project type",
      "Add approval workflows as conditional form fields",
      "Embed links to shared drives and project boards",
      "Adjust sections for different industries or methodologies",
    ],
  },
  4: {
    overview:
      "The Client Onboarding Document Kit provides a complete, repeatable onboarding workflow built in Canva-ready format. It bundles every template needed to move a new client from first contact to active engagement—including intake questionnaires, welcome letters, scope of work agreements, communication preference forms, and asset request checklists. Every document follows the same professional tone and branding structure so new clients feel welcomed from day one.",
    whatsIncluded: [
      "Client intake and discovery questionnaire",
      "Welcome letter and onboarding confirmation template",
      "Scope of work and service agreement outline",
      "Contact and emergency information form",
      "Brand and asset request checklist",
      "Timeline and project launch schedule",
      "Client communication preferences form",
      "Follow-up and feedback request template",
    ],
    templateFeatures: [
      "Canva-ready templates with drag-and-drop editing",
      "Consistent branding and tone across all documents",
      "Sequential numbering with clear logical flow",
      "Email-ready formatting for instant delivery",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Canva", "PDF"],
    idealFor: [
      "Freelancers scaling client acquisition professionally",
      "Agencies standardizing intake across account managers",
      "Consultants who need a polished first impression",
    ],
    keyBenefits: [
      "Reduces onboarding time with a proven reusable workflow",
      "Eliminates follow-up emails chasing missing information",
      "Projects organization and professionalism to every new client",
      "Fully customizable to match your service tiers and brand",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Canva", "PDF"],
    customizationOptions: [
      "Add your logo and brand colors to every document",
      "Customize intake questions to match service tiers",
      "Create electronic signature fields using DocuSign or similar",
      "Duplicate templates for different client types or service lines",
    ],
  },
  5: {
    overview:
      "The Employee Handbook Starter Template gives founders and HR managers a structured, compliant foundation for documenting company culture, policies, and expectations. It covers everything from employment classifications, codes of conduct, and benefits to health and safety procedures. Written in accessible language, this handbook balances legal structure with readability so employees actually engage with the content rather than skip it.",
    whatsIncluded: [
      "Table of contents with auto-linked sections",
      "Welcome and company mission statement section",
      "Employment classification and equal opportunity policies",
      "Code of conduct and workplace expectations",
      "Benefits, time off, and leave policies",
      "Health, safety, and emergency procedures",
      "Performance expectations and review cycles",
      "Acknowledgment and receipt page",
    ],
    templateFeatures: [
      "Modular section layout for easy additions and updates",
      "Policy numbering system supporting cross-references",
      "Editable tables for benefits and holiday schedules",
      "Print-ready and email-shareable formats",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Apple Pages", "PDF"],
    idealFor: [
      "Startup founders building their first employee handbook",
      "HR managers updating an outdated or fragmented handbook",
      "Growing teams adding structure to onboarding programs",
    ],
    keyBenefits: [
      "Establishes clear expectations and reduces HR ambiguity",
      "Professional appearance that builds employee trust",
      "Modular design grows with your company",
      "Legal framework supporting compliance and fair treatment",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Apple Pages", "PDF"],
    customizationOptions: [
      "Tailor policies to state and local employment laws",
      "Add company-specific benefits and PTO policies",
      "Include photos, team values, and culture pages",
      "Create digital versions with clickable navigation",
    ],
  },
  6: {
    overview:
      "The Business Process Map Template Set gives teams a visual language for documenting how work moves through the organization. Rather than describing processes in paragraphs, these editable flowchart templates capture handoffs, decision points, approvals, and bottlenecks as clean diagrammatic maps. Use them to document existing workflows, identify inefficiencies, and train new hires on how work is intended to flow.",
    whatsIncluded: [
      "Linear process flow template",
      "Swimlane cross-functional map template",
      "Decision-tree flowchart template",
      "Input-output process diagram template",
      "Milestone and phase-gate template",
      "RACI-style responsibility assignment map",
      "Root cause analysis diagram",
      "Process improvement before-and-after map",
    ],
    templateFeatures: [
      "Editable flowchart shapes and connector lines",
      "Color-coded swimlanes for different departments",
      "Decision diamond templates with Yes and No paths",
      "Grid-snap connection lines for clean alignment",
    ],
    compatibleSoftware: ["Microsoft Visio", "Lucidchart", "Diagram.net", "Canva", "PowerPoint"],
    idealFor: [
      "Operations teams mapping current-state workflows",
      "Project managers designing approval or escalation paths",
      "Lean practitioners documenting value streams",
    ],
    keyBenefits: [
      "Turns tribal knowledge into visual instructions anyone can follow",
      "Exposes bottlenecks and redundancies in existing workflows",
      "Professional enough for board presentations and audits",
      "Saves hours of manual diagramming from scratch",
    ],
    fileFormats: ["Visio (.vsdx)", "PDF", "PowerPoint (.pptx)", "Canva"],
    customizationOptions: [
      "Adjust shapes, colors, and labels to match branding",
      "Add or remove process steps as workflows evolve",
      "Export as high-resolution images for presentations",
      "Link to supporting documents in shared workspaces",
    ],
  },
  7: {
    overview:
      "The Standard Operating Procedure Library (20 SOPs) is the fastest way to move from tribal knowledge to documented operations. This collection includes twenty ready-to-customize SOPs spanning the most common business functions—from employee onboarding and customer support to inventory management and quality assurance. Every SOP follows the same disciplined structure, so teams learn one format and apply it consistently across the entire organization.",
    whatsIncluded: [
      "Customer onboarding SOP",
      "New hire onboarding SOP",
      "Daily opening and closing checklist SOP",
      "Quality inspection SOP",
      "Inventory management and stock count SOP",
      "Customer support escalation SOP",
      "Incident reporting SOP",
      "Content publishing workflow SOP",
      "Financial reconciliation SOP",
      "Equipment maintenance SOP",
      "Data backup and recovery SOP",
      "Client follow-up SOP",
      "Expense reporting SOP",
      "Vendor evaluation SOP",
      "Training delivery SOP",
      "Compliance audit checklist SOP",
      "Social media management SOP",
      "Meeting facilitation SOP",
      "Return and refund processing SOP",
      "Product launch checklist SOP",
    ],
    templateFeatures: [
      "Standardized SOP format across all 20 documents",
      "Numbered steps, responsible roles, and frequency fields",
      "Revision history table on every SOP",
      "Printable and digital-ready layouts",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "PDF"],
    idealFor: [
      "Businesses formalizing operations for the first time",
      "Teams preparing for audits, certifications, or scaling",
      "Founders who need documented processes before hiring",
    ],
    keyBenefits: [
      "Twenty core SOPs covering your busiest functions",
      "Consistent structure eliminates format debates",
      "Ready to customize and deploy immediately",
      "Builds a culture of written accountability",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Adapt language and steps to your exact workflow",
      "Insert your logo and company branding",
      "Create a custom numbering and naming system",
      "Combine related SOPs into larger operations manuals",
    ],
  },
  8: {
    overview:
      "The Department Operations Manual Template gives department leads a structured framework for documenting how their team operates day to day. Whether you run operations, customer success, marketing, or finance, this template helps you capture responsibilities, workflows, key metrics, and team rhythms in one place. It can be handed to a new manager so they can understand and inherit the operation without a multi-month transition period.",
    whatsIncluded: [
      "Department overview and mission section",
      "Team structure and reporting lines",
      "Core operational workflows and process maps",
      "Key performance indicators and reporting cadence",
      "Resources, tools, and systems inventory",
      "Roles and responsibilities matrix",
      "Meeting rhythm and decision rights",
      "Emergency procedures and escalation paths",
    ],
    templateFeatures: [
      "Department-specific layout with clear section hierarchy",
      "Editable org chart and RACI table templates",
      "Dashboard-ready KPI tracker with metric definitions",
      "Resource inventory table with access instructions",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "PDF"],
    idealFor: [
      "Department heads documenting their operational model",
      "Operations and customer success teams scaling structure",
      "Managers inheriting a new department or region",
    ],
    keyBenefits: [
      "Accelerates manager onboarding by weeks instead of months",
      "Creates a durable record that survives turnover",
      "Aligns the team on roles, metrics, and escalation paths",
      "Professional document suitable for leadership review",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Rebrand with department logos and color coding",
      "Add department-specific SOP references and links",
      "Include screenshots and walkthroughs of internal tools",
      "Create version-controlled updates for quarterly reviews",
    ],
  },
  9: {
    overview:
      "The Vendor & Supplier Agreement Framework provides structured, clause-ready templates for formalizing vendor and supplier relationships with clear terms, responsibilities, and evaluation criteria. Whether onboarding a new software provider or reviewing a physical supplier contract, this framework ensures every relationship starts with mutual understanding—covering service levels, confidentiality, payment terms, and performance evaluation in one organized package.",
    whatsIncluded: [
      "Standard vendor service agreement template",
      "Master service agreement outline",
      "Non-disclosure and confidentiality agreement",
      "Supplier performance evaluation checklist",
      "Service level agreement (SLA) template",
      "Request for proposal (RFP) response tracker",
      "Vendor onboarding checklist",
      "Contract renewal and exit evaluation form",
    ],
    templateFeatures: [
      "Clause-ready legal structure with placeholder areas",
      "Editable terms for services, fees, and termination",
      "Built-in evaluation scoring tables",
      "Signature and witness block formatting",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "PDF"],
    idealFor: [
      "Procurement teams formalizing vendor relationships",
      "Operations managers overseeing multiple suppliers",
      "Legal and compliance teams standardizing contract review",
    ],
    keyBenefits: [
      "Reduces contract review time with pre-structured agreements",
      "Ensures consistent terms across all vendor relationships",
      "Protects the business with standard legal provisions",
      "Streamlines supplier onboarding and evaluation",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "PDF"],
    customizationOptions: [
      "Adapt clauses to your legal review and jurisdiction",
      "Add company-specific insurance and liability requirements",
      "Insert branding and letterhead",
      "Create clause libraries for different vendor categories",
    ],
  },
  10: {
    overview:
      "The Complete HR Document Pack is a comprehensive collection of hiring, onboarding, and personnel documentation templates designed for growing teams that have outgrown ad-hoc processes. From job descriptions, offer letters, and NDAs to performance reviews and offboarding checklists, this pack gives HR managers and founders a complete document library that stays consistent from candidate outreach through employee exit.",
    whatsIncluded: [
      "Job description templates for multiple role types",
      "Employment offer letter template",
      "New hire paperwork checklist",
      "Employee personal information form",
      "NDA and confidentiality agreement",
      "Employee handbook acknowledgment form",
      "Performance review template (annual and quarterly)",
      "Disciplinary action documentation form",
      "Employee exit interview checklist",
      "Final pay and return-of-property form",
    ],
    templateFeatures: [
      "Compliant language aligned with US employment standards",
      "Consistent formatting across all HR documents",
      "Checklist-style layouts for onboarding and exit flows",
      "Signature-ready agreement templates",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "PDF"],
    idealFor: [
      "Growing startups building their first HR library",
      "Small business owners managing hiring without dedicated HR staff",
      "HR managers standardizing people operations",
    ],
    keyBenefits: [
      "Covers the full employee lifecycle in one organized pack",
      "Reduces administrative time with ready-to-send templates",
      "Professional templates that reflect well on your employer brand",
      "Consistent documentation protects against compliance gaps",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "PDF"],
    customizationOptions: [
      "Edit roles, benefits, and policy language to match your company",
      "Add your logo and branded letterhead",
      "Create role-specific offer letter templates",
      "Adapt review forms for different performance frameworks",
    ],
  },
  11: {
    overview:
      "The Business Playbook Template System is a structured framework for capturing how your business actually runs, department by department. Rather than storing institutional knowledge in individual heads, this system gives founders and operators a repeatable playbook format covering marketing workflows, sales scripts, customer support protocols, and product release procedures. It is the closest thing to a written operating system for your business.",
    whatsIncluded: [
      "Core business playbook structure and table of contents",
      "Marketing playbook section template",
      "Sales playbook and objection-handling template",
      "Customer support playbook template",
      "Product and engineering playbook template",
      "Finance and operations playbook template",
      "People and culture playbook template",
      "Performance tracking and review section",
    ],
    templateFeatures: [
      "Department-specific section architecture",
      "Editable playbook templates with consistent formatting",
      "Cheat sheet and quick-reference inserts",
      "Version control and update log templates",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "PDF"],
    idealFor: [
      "Founders capturing institutional knowledge before scaling",
      "Operations teams standardizing department functions",
      "Consultants delivering structured playbooks to clients",
    ],
    keyBenefits: [
      "Survives staff turnover by documenting how work gets done",
      "Unifies department language and expectations",
      "Reduces training time for new hires and managers",
      "Built for continuous improvement and versioning",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "PDF"],
    customizationOptions: [
      "Build out one section at a time as each department matures",
      "Add department-specific scripts and template libraries",
      "Embed links to external tools and shared resources",
      "Create read-only viewer versions for new hires and contractors",
    ],
  },
  12: {
    overview:
      "The Full Operations Document Suite combines standard operating procedures, process maps, and operations manuals into a single comprehensive package for teams ready to standardize end to end. Rather than buying components separately, this suite delivers a unified library where every SOP, process map, and manual follows the same structure. It is the right choice for operations teams that have moved beyond patchwork documentation and are ready for a cohesive system.",
    whatsIncluded: [
      "Twenty canonical SOP templates",
      "Eighteen process map templates (flowcharts and swimlanes)",
      "Four department operations manual structures",
      "RACI and responsibility matrix templates",
      "Meeting cadence and review schedule templates",
      "Performance dashboard and KPI tracker",
      "Issue log and continuous improvement log",
      "Master index and document control framework",
    ],
    templateFeatures: [
      "Unified numbering and naming convention across all documents",
      "Cross-linked table of contents and master index",
      "Consistent branding and formatting throughout",
      "Version control log for every document type",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Microsoft Visio", "Notion", "PDF"],
    idealFor: [
      "Mid-size companies formalizing their entire operations layer",
      "Operations directors preparing for audits or certifications",
      "Teams migrating from tribal knowledge to written systems",
    ],
    keyBenefits: [
      "Everything in one package with consistent structure",
      "Eliminates the time cost of selecting individual templates",
      "Creates an operations backbone that scales with the business",
      "Professional enough for leadership review and investor audits",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Visio (.vsdx)", "Notion", "PDF"],
    customizationOptions: [
      "Add or remove SOPs based on operational priorities",
      "Create department-specific sub-libraries",
      "Brand the entire suite with your company standards",
      "Link process maps to their corresponding SOP pages",
    ],
  },
  13: {
    overview:
      "The Franchise Operations Manual Template gives multi-location operators a consistent, repeatable manual framework for training, running, and evaluating every location the same way. Franchise operators know that inconsistent execution is the fastest way to erode brand value. This manual ensures every location owner and manager receives the same structured guidance on standards, procedures, marketing, and compliance—protecting your brand while giving franchisees a clear roadmap to success.",
    whatsIncluded: [
      "Franchise overview and brand standards section",
      "Daily, weekly, and monthly operational checklists by department",
      "Training program and certification tracker",
      "Quality assurance and audit checklist",
      "Marketing and local advertising guidelines",
      "Financial and reporting requirements template",
      "Supplier and procurement standards",
      "Franchisee compliance and renewal review",
    ],
    templateFeatures: [
      "Multi-location scalable structure",
      "Checklist-based execution pages for managers",
      "Audit and compliance scoring templates",
      "Read-only field guides for franchisee staff",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "PDF"],
    idealFor: [
      "Franchisors building their first operations manual",
      "Multi-location restaurant, retail, or service operators",
      "Franchise consultants delivering compliance-ready documents",
    ],
    keyBenefits: [
      "Protects brand consistency across every location",
      "Reduces franchisee support time with self-service documentation",
      "Structured enough for legal and insurance review",
      "Supports scalable training without reinventing content",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "PDF"],
    customizationOptions: [
      "Adapt standards to your industry and brand requirements",
      "Create location-specific addenda and supplements",
      "Add franchise fee and royalty calculation tables",
      "Include video and image placeholders for franchisee reference",
    ],
  },
  14: {
    overview:
      "The Enterprise SOP + Process Map Bundle is built for organizations documenting operations at scale. This bundle pairs a full SOP library with matching process map templates, giving you two complementary views of every major workflow: the written procedure and the visual flowchart. Enterprise teams use this bundle to standardize complex, cross-functional operations while maintaining the ability to visualize handoffs, data flows, and decision paths for leadership review, audits, and continuous improvement.",
    whatsIncluded: [
      "Thirty enterprise-grade SOP templates",
      "Thirty matching process map templates (flowcharts and swimlanes)",
      "Cross-functional workflow documentation guide",
      "Data flow and system integration map templates",
      "Risk assessment and control matrix",
      "Document control and master index",
      "Change request and SOP update tracker",
      "Audit and compliance review templates",
    ],
    templateFeatures: [
      "Enterprise-grade formatting with executive-ready polish",
      "Layered documentation: summary, detailed, and visual views",
      "Advanced tables for risks, controls, and KPIs",
      "Archived change management and revision tracking",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Microsoft Visio", "Lucidchart", "PDF"],
    idealFor: [
      "Enterprise operations teams documenting complex workflows",
      "Organizations preparing for ISO, SOC 2, or compliance audits",
      "Consultants implementing operations frameworks at scale",
    ],
    keyBenefits: [
      "Two complementary views of every major workflow",
      "Meets the documentation depth expected by enterprise auditors",
      "Scales across departments and geographies",
      "Reduces consulting costs by providing a complete starting framework",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Visio (.vsdx)", "Lucidchart", "PDF"],
    customizationOptions: [
      "Create department-specific SOP libraries",
      "Integrate process maps with your internal wiki or intranet",
      "Build approval workflows for SOP changes",
      "Develop SOP templates for new business units as you expand",
    ],
  },
  15: {
    overview:
      "The Complete Business Document Library is the definitive catalog of document templates, SOPs, and process maps in one organized, searchable collection. Instead of purchasing individual systems, this library gives you access to every template type in the catalog—from single-page SOPs to full operations manuals—so you can assemble exactly the documentation stack your business needs. It is the centerpiece of a professional operations infrastructure.",
    whatsIncluded: [
      "All document templates from the Template category",
      "All SOP systems across all pricing tiers",
      "All process map sets and flowchart libraries",
      "All business kit collections",
      "Master index and quick-reference guide",
      "Style guide and formatting standards",
      "Template usage and best-practice guide",
      "Regular update notifications as the library expands",
    ],
    templateFeatures: [
      "Unified master index with hyperlinked navigation",
      "Consistent formatting and naming across all collections",
      "Modular design lets you assemble custom kits",
      "Frequently updated with new templates and formats",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "Canva", "Microsoft Visio", "PDF"],
    idealFor: [
      "Operations professionals who need access to every template type",
      "Businesses that want to assemble custom documentation stacks",
      "Consultants delivering comprehensive client documentation",
    ],
    keyBenefits: [
      "The most complete single-purchase documentation library available",
      "Modular enough to build exactly what you need",
      "Saves money compared to purchasing systems separately",
      "Grows with your business as you add new documentation needs",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "Canva", "Visio (.vsdx)", "PDF"],
    customizationOptions: [
      "Assemble custom kits from template subsets",
      "Create white-labeled versions for client delivery",
      "Add internal SOPs to the master index",
      "Build department-specific plays from the template library",
    ],
  },
  16: {
    overview:
      "The Ultimate Workflow & Operations System is the most comprehensive document and operations package available, combining every template, SOP, and process map into a single end-to-end operations system. This is the system for organizations that are no longer experimenting with documentation and are ready to deploy a complete, structured infrastructure covering onboarding, operations, quality, compliance, and continuous improvement.",
    whatsIncluded: [
      "All fifty-plus document templates from the full catalog",
      "All SOP systems and process map libraries",
      "All business kit collections and automation frameworks",
      "Enterprise operations manual framework",
      "Business playbook and knowledge management system",
      "Franchise and multi-location operations manual",
      "Continuous improvement and Kaizen tracking system",
      "Master index, style guide, and governance framework",
      "Implementation roadmap and rollout guide",
      "Priority access to future template updates",
    ],
    templateFeatures: [
      "Enterprise-grade design with executive polish",
      "Integrates every template, SOP, and map into one system",
      "Built-in governance, version control, and update cadence",
      "Implementation roadmap and change management guide",
    ],
    compatibleSoftware: ["Microsoft Word (.docx)", "Google Docs", "Notion", "Canva", "Microsoft Visio", "Lucidchart", "PDF"],
    idealFor: [
      "Fast-growing companies formalizing their entire operations stack",
      "Enterprise teams needing a complete documentation ecosystem",
      "Consultants delivering turnkey operational systems to clients",
    ],
    keyBenefits: [
      "The only purchase needed for a complete operations library",
      "Eliminates search costs and integration gaps between systems",
      "Designed for scale, audit, and investor readiness",
      "Future-proof with included updates and new template access",
    ],
    fileFormats: ["Word (.docx)", "Google Docs", "Notion", "Canva", "Visio (.vsdx)", "Lucidchart", "PDF"],
    customizationOptions: [
      "Assemble subsets for specific business units or divisions",
      "Brand the entire system to your corporate identity",
      "Add proprietary templates and integrate with your wiki",
      "Create implementation phases for large-scale rollouts",
    ],
  },
};
