export type Product = {
  id: number;
  slug: string;
  name: string;
  price: number;
  category: string;
  sizes: string[] | null;
  image: string;
  images: string[];
  altText: string;
  downloadFile: string | null;
};

export const FALLBACK_CATEGORIES: string[] = ["Document Templates", "SOP Systems", "Process Maps", "Business Kits"];

export const FALLBACK_PRODUCTS: Product[] = [
  { id: 1, slug: "single-page-sop-template-starter-1", name: "Single-Page SOP Template — Starter", price: 9.99, category: "SOP Systems", sizes: null, image: "/images/products/1-single-page-sop-starter.jpg", images: ["/images/products/1-single-page-sop-starter.jpg"], altText: "Single-page SOP template preview showing a clean structured layout with process steps, approval sections, and notes fields", downloadFile: null },
  { id: 2, slug: "meeting-agenda-pack-10-templates-2", name: "Meeting Agenda Pack (10 Templates)", price: 13.95, category: "Document Templates", sizes: null, image: "/images/products/2-meeting-agenda-pack.jpg", images: ["/images/products/2-meeting-agenda-pack.jpg"], altText: "Meeting agenda templates preview showing structured layouts for standups, planning, and leadership review meetings", downloadFile: null },
  { id: 3, slug: "project-brief-document-template-3", name: "Project Brief Document Template", price: 14.75, category: "Document Templates", sizes: null, image: "/images/products/3-project-brief-template.jpg", images: ["/images/products/3-project-brief-template.jpg"], altText: "Project brief document template preview displaying structured project scope, timeline, ownership, and approval sections", downloadFile: null },
  { id: 4, slug: "client-onboarding-document-kit-4", name: "Client Onboarding Document Kit", price: 17.95, category: "Document Templates", sizes: null, image: "/images/products/4-client-onboarding-kit.jpg", images: ["/images/products/4-client-onboarding-kit.jpg"], altText: "Client onboarding document kit preview showing professional intake forms, welcome letters, and service agreement templates", downloadFile: null },
  { id: 5, slug: "employee-handbook-starter-template-5", name: "Employee Handbook Starter Template", price: 18.75, category: "Document Templates", sizes: null, image: "/images/products/5-employee-handbook-starter.jpg", images: ["/images/products/5-employee-handbook-starter.jpg"], altText: "Employee handbook template preview showing structured policy sections, conduct guidelines, and onboarding framework", downloadFile: null },
  { id: 6, slug: "business-process-map-template-set-6", name: "Business Process Map Template Set", price: 28.76, category: "Process Maps", sizes: null, image: "/images/products/6-business-process-map.png", images: ["/images/products/6-business-process-map.png"], altText: "Business process map template set preview displaying editable flowchart layouts for organizational handoffs and decisions", downloadFile: "/downloads/business-process-map-templates.pdf" },
  { id: 7, slug: "standard-operating-procedure-library-20-sops-7", name: "Standard Operating Procedure Library (20 SOPs)", price: 38.64, category: "SOP Systems", sizes: null, image: "/images/products/7-sop-library-20sops.jpg", images: ["/images/products/7-sop-library-20sops.jpg"], altText: "Standard operating procedure library preview showing twenty ready-to-customize SOP document templates across business operations", downloadFile: "/downloads/sop-library.pdf" },
  { id: 8, slug: "department-operations-manual-template-8", name: "Department Operations Manual Template", price: 47.89, category: "SOP Systems", sizes: null, image: "/images/products/8-department-operations-manual.jpg", images: ["/images/products/8-department-operations-manual.jpg"], altText: "Department operations manual template preview showing an organized framework for documenting team responsibilities and workflows", downloadFile: null },
  { id: 9, slug: "vendor-supplier-agreement-framework-9", name: "Vendor & Supplier Agreement Framework", price: 49.76, category: "Document Templates", sizes: null, image: "/images/products/9-vendor-supplier-agreement.png", images: ["/images/products/9-vendor-supplier-agreement.png"], altText: "Vendor and supplier agreement framework preview with structured contract templates, evaluation checklists, and service level forms", downloadFile: null },
  { id: 10, slug: "complete-hr-document-pack-10", name: "Complete HR Document Pack", price: 53.45, category: "Business Kits", sizes: null, image: "/images/products/10-complete-hr-document-pack.jpg", images: ["/images/products/10-complete-hr-document-pack.jpg"], altText: "Complete HR document pack preview bundling core hiring, onboarding, personnel, and policy documentation templates", downloadFile: null },
  { id: 11, slug: "business-playbook-template-system-11", name: "Business Playbook Template System", price: 54.95, category: "Business Kits", sizes: null, image: "/images/products/11-business-playbook-template.jpg", images: ["/images/products/11-business-playbook-template.jpg"], altText: "Business playbook template system preview displaying a structured department-by-department framework for capturing operating knowledge", downloadFile: null },
  { id: 12, slug: "full-operations-document-suite-12", name: "Full Operations Document Suite", price: 86.88, category: "Business Kits", sizes: null, image: "/images/products/12-full-operations-document-suite.png", images: ["/images/products/12-full-operations-document-suite.png"], altText: "Full operations document suite preview combining SOPs, process maps, and operations manuals into one comprehensive business system", downloadFile: null },
  { id: 13, slug: "franchise-operations-manual-template-13", name: "Franchise Operations Manual Template", price: 87.64, category: "SOP Systems", sizes: null, image: "/images/products/13-franchise-operations-manual.jpg", images: ["/images/products/13-franchise-operations-manual.jpg"], altText: "Franchise operations manual template preview showing a consistent multi-location framework for training and brand standardization", downloadFile: null },
  { id: 14, slug: "enterprise-sop-process-map-bundle-14", name: "Enterprise SOP + Process Map Bundle", price: 87.76, category: "Process Maps", sizes: null, image: "/images/products/14-enterprise-sop-process-map-bundle.png", images: ["/images/products/14-enterprise-sop-process-map-bundle.png"], altText: "Enterprise SOP and process map bundle preview pairing a full SOP library with matching flowchart templates for large-scale operations", downloadFile: null },
  { id: 15, slug: "complete-business-document-library-15", name: "Complete Business Document Library", price: 94.82, category: "Business Kits", sizes: null, image: "/images/products/15-complete-business-document-library.png", images: ["/images/products/15-complete-business-document-library.png"], altText: "Complete business document library preview showing an organized collection covering every template category from SOPs to process maps", downloadFile: null },
  { id: 16, slug: "ultimate-workflow-operations-system-16", name: "Ultimate Workflow & Operations System", price: 96.95, category: "Business Kits", sizes: null, image: "/images/products/16-ultimate-workflow-operations-system.png", images: ["/images/products/16-ultimate-workflow-operations-system.png"], altText: "Ultimate workflow and operations system preview displaying the most complete end-to-end operations suite combining every template and SOP", downloadFile: null }
];

export const hasSizeGuide = false;
